name: Versioning and Documentation
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  build:
    outputs:
      version: ${{ steps.buildUpdate.outputs.v }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Run module maintenance script
        id: buildUpdate
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyPS
          $loc = Get-Location
          $Env:PSModulePath = $Env:PSModulePath+":$loc"
          Import-Module -name verkadaModule
          $output = (./maintenance/updateMod.ps1)
          echo "v=$output" >> $env:GITHUB_OUTPUT
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Bumping release to ${{ steps.buildUpdate.outputs.v }}